fetchChart:
    path: /con4gis/fetchchart/{chartId}
    defaults:
        _scope: frontend
        _controller: "con4gisVisualizationBundle:Chart:fetch"
        methods: [GET]
    requirements:
      chartId: '\d+'

testFetchChart:
    path: /con4gis/testfetchchart/
    defaults:
        _scope: frontend
        _controller: "con4gisVisualizationBundle:Chart:testFetch"
        methods: [GET]
    requirements:
        chartId: '\d+'