services:
  _defaults:
    autowire: true
    autoconfigure: true

  # allow Contao Database to be autowired
  Contao\Database:
    factory: [ 'Contao\Database', 'getInstance' ]
    public: true
    lazy: false

  con4gis.chart_service:
    class: con4gis\VisualizationBundle\Classes\Services\ChartBuilderService
    public: true
    arguments:
      - "@logger"

  con4gis\VisualizationBundle\Controller\ChartController:
    class: con4gis\VisualizationBundle\Controller\ChartController
    tags: [ 'controller.service_arguments' ]
    public: true
    calls:
      - setContainer: [ '@service_container' ]
    arguments:
      - "@service_container"
      - "@contao.framework"
      - "@logger"
      - "@con4gis.chart_service"
