services:
  _defaults:
    autowire: true
    autoconfigure: true

  # allow Contao Database to be autowired
  Contao\Database:
    factory: [ 'Contao\Database', 'getInstance' ]
    public: true
    lazy: true

  con4gis\VisualizationBundle\Controller\:
    resource: '../../Controller'
    tags: [ 'controller.service_arguments' ]

  con4gis\VisualizationBundle\Services\:
    resource: '../../Services'
